/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface CCoffeeIcon {}
  interface CCoffeeIconAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'CCoffeeIcon': Components.CCoffeeIcon;
  }

  interface StencilIntrinsicElements {
    'c-coffee-icon': Components.CCoffeeIconAttributes;
  }


  interface HTMLCCoffeeIconElement extends Components.CCoffeeIcon, HTMLStencilElement {}
  var HTMLCCoffeeIconElement: {
    prototype: HTMLCCoffeeIconElement;
    new (): HTMLCCoffeeIconElement;
  };

  interface HTMLElementTagNameMap {
    'c-coffee-icon': HTMLCCoffeeIconElement
  }

  interface ElementTagNameMap {
    'c-coffee-icon': HTMLCCoffeeIconElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
